__use_yte__: true

max-in-memory-rows: 5000

name: DMR regions
datasets:
  genes_transcripts:
    path: ?input.genes_transcripts
    separator: "\t"
  regulations:
    path: ?input.regulations
    separator: "\t"
default-view: genes_transcripts
views:
  genes_transcripts:
    dataset: genes_transcripts
    desc: |
      Differentially methylated region between the two experiments under consideration  annotated with genes/transcripts.
    page-size: 25
    render-table:
      columns:
        chr:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: tableau20
        p(MWU):
          display-mode: hidden
        p(2DKS):
          display-mode: hidden
        seqif:
          display-mode: hidden
        score:
          display-mode: hidden
        strand:
          display-mode: hidden
        phase:
          display-mode: hidden
        mean_g1:
          display-mode: hidden
        mean_g2:
          display-mode: hidden             
        number_CpGs:
          display-mode: hidden          
        q-value:
          plot:
            heatmap:
              scale: linear
              range:
                - "#a1d99b"
                - "white"
                - "#fdae6b"
              domain:
                - 0
                - 0.05
                - 0.25
        mean_methylation_difference:
          plot:
            heatmap:
              scale: linear
              range:
                - "#e6550d"
                - "white"
                - "#6baed6"
              domain:
                - -1
                - 0
                - 1 
        type:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: tableau20
        source:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: tableau20
        ID:
          display-mode: hidden
        biotype:
          display-mode: hidden
        tag:
          display-mode: hidden
        transcript_support_level:
          display-mode: hidden
        version:
          display-mode: hidden
        ccdsid:
          display-mode: hidden
        transcript_id:
          display-mode: hidden
        Parent:
          display-mode: hidden
        Name:
          label: "feature"
          link-to-url: 
            Ensembl:
              url: "http://www.ensembl.org/Homo_sapiens/Gene/Summary?g={transcript_id}"
        source:
          display-mode: detail
        start_feature:
          display-mode: detail
        end_feature:
          display-mode: detail
        absolute_signed_pi_val:
          display-mode: hidden
  regulations:
    dataset: regulations
    desc: |
      Differentially methylated region between the two experiments under consideration annotated with genes/transcripts.
    page-size: 25
    render-table:
      columns:
        chr:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: tableau20
        p(MWU):
          display-mode: hidden
        p(2DKS):
          display-mode: hidden
        seqif:
          display-mode: hidden
        score:
          display-mode: hidden
        strand:
          display-mode: hidden
        phase:
          display-mode: hidden
        mean_g1:
          display-mode: hidden
        mean_g2:
          display-mode: hidden             
        number_CpGs:
          display-mode: hidden          
        q-value:
          plot:
            heatmap:
              scale: linear
              range:
                - "#a1d99b"
                - "white"
                - "#fdae6b"
              domain:
                - 0
                - 0.05
                - 0.25
        mean_methylation_difference:
          plot:
            heatmap:
              scale: linear
              range:
                - "#e6550d"
                - "white"
                - "#6baed6"
              domain:
                - -1
                - 0
                - 1 
        type:
          link-to-url: 
            Ensembl:
              url: "https://www.ensembl.org/Homo_sapiens/Regulation/Summary?fdb=funcgen;r=7:50781435-50784400;rf={ID}"
        source:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: tableau20
        extended_start:
          display-mode: hidden
        extended_end:
          display-mode: hidden
        color:
          display-mode: hidden
        ID:
          display-mode: hidden
        source:
          display-mode: detail
        start_feature:
          display-mode: detail
        end_feature:
          display-mode: detail
        gene_id:
          display-mode: hidden
        gene_name:
          link-to-url: 
            Ensembl:
              url: "http://www.ensembl.org/Homo_sapiens/Gene/Summary?g={gene_id}"
        gene_biotype:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: tableau20
        absolute_signed_pi_val:
          display-mode: hidden