name: DMR regions
datasets:
  dmrs:
    path: ?input.table

default-view: dmrs
views:
  dmrs:
    dataset: dmrs
    desc: |
      ### DMR regions blablabla
    page-size: 25
    render-table:
      columns:
        index(0):
          display-mode: hidden