
# https://github.com/varlociraptor/varlociraptor-methylation-evaluation

sample:
  species: "homo_sapiens"
  datatype: "dna"
  build: "GRCh38"
  release: "110"
  chromosome: "21"

scatter_items: 100

# base_dir: "/home/adrian//Documents/Promotion/"
# varlo_path: "/home/adrian//Documents/Promotion/varlociraptor/"
# pipeline_path: "/home/adrian/Documents/Promotion/data_analysis/snakemake-workflow-template"
# sample_path: "/home/adrian/Documents/Promotion/data_analysis/snakemake-workflow-template/resources/sample.tsv"


base_dir: "/projects/koesterlab/benchmark-methylation/data_analysis_jochen"
varlo_path: "/projects/koesterlab/benchmark-methylation/data_analysis_jochen/varlociraptor/"
pipeline_path: "/projects/koesterlab/benchmark-methylation/data_analysis_jochen/compare_meth/"
sample_path: "/projects/koesterlab/benchmark-methylation/data_analysis_jochen/compare_meth/resources/sample.tsv"

ref_sample: "BC01-ref-sorted"
ref_sample_number: "BC01"

#########################################
# For enrichment

resources:
  ref:
    # ensembl species name
    species: homo_sapiens
  ontology:
    # gene ontology to download, used e.g. in goatools
    gene_ontology: "http://current.geneontology.org/ontology/go-basic.obo"


enrichment:
  goatools:
    # tool is only run if set to `true`
    activate: true
    fdr_genes: 0.05
    fdr_go_terms: 0.05
  fgsea:
    # tool is only run if set to `true`
    activate: false
    # if activated, you need to provide a GMT file with gene sets of interest
    gene_sets_file: "resources/gene_sets/dummy.gmt"
    fdr_gene_set: 0.05
    # minimum achievable p-value  (equivalent to the reciprocal of the number of permutations, see fgsea docs)
    eps: 1.0e-50
  spia:
    # tool is only run if set to `true`
    activate: true
    # pathway database to use in SPIA, needs to be available for
    # the species specified by resources -> ref -> species above
    pathway_database: "reactome"
    # OrgDB Genome wide annotation package (https://www.bioconductor.org/packages/release/BiocViews.html#___OrgDb) for the species under consideration. Only required if you want to have a gene analysis for your pathways. Else NA
    orgDb: org.Mm.eg.db