
# https://github.com/varlociraptor/varlociraptor-methylation-evaluation

sample:
  species: "homo_sapiens"
  datatype: "dna"
  build: "GRCh38"
  release: "110"
  chromosome: "21"

scatter_items: 100

# base_dir: "/home/adrian//Documents/Promotion/"
# varlo_path: "/home/adrian//Documents/Promotion/varlociraptor/"
# pipeline_path: "/home/adrian/Documents/Promotion/data_analysis/snakemake-workflow-template"
# sample_path: "/home/adrian/Documents/Promotion/data_analysis/snakemake-workflow-template/resources/sample.tsv"


base_dir: "/projects/koesterlab/benchmark-methylation/data_analysis_jochen"
varlo_path: "/projects/koesterlab/benchmark-methylation/data_analysis_jochen/varlociraptor/"
pipeline_path: "/projects/koesterlab/benchmark-methylation/data_analysis_jochen/compare_meth/"
sample_path: "/projects/koesterlab/benchmark-methylation/data_analysis_jochen/compare_meth/resources/sample.tsv"

ref_sample: "BC01-ref-sorted"
ref_sample_number: "BC01"